# Site settings
title: 'Site title'
name: 'My name'
description: 'I am amazing.'

# Delete or comment the lines you don't need
facebook: ''
twitter: ''
linkedin: ''
instagram: ''
flickr: ''
github: ''
#codepen: ''
#telegram: ''
#keybase: ''
#steam: ''
#soundcloud: ''
#stack-overflow: ''
#reddit: ''
#medium:  ''
#tumblr: ''
weibo: ''
vk: ''
#lastfm: ''
blog_url: ''
email: ''

avatar: 'assets/images/avatar.jpg'
background: 'assets/images/background.jpg'
favicon: 'assets/images/favicon.ico'

# Advanced site settings
baseurl: '/cover-card'
markdown: kramdown
permalink: pretty
remote_theme: epidrome/cover-card
plugins:
  - jekyll-remote-theme
