# Site settings
title: 'Site title'
name: 'My name'
description: 'I am amazing.'
url: ''
remote_theme: epidrome/front-cover

# Delete the lines you don't need
# edit the _include/too_social.html to add more profiles
github_username: ''
telegram_username: ''
keybase_username: ''

avatar: yes
avatar_img_path: 'assets/images/avatar.jpg'

front_img: yes
front_img_path: 'assets/images/background.jpg'

favicon_img: yes
favicon_img_path: 'assets/images/favicon.ico'

# Build settings
markdown: kramdown
permalink: pretty
