# Theme
remote_theme: epidrome/cover-card

# Title and tag line 
title: 'My name'
description: 'I am amazing.'

# Images
avatar: 'avatar.jpg'
background: 'background.jpg'
favicon: 'favicon.ico'

# Online profiles
facebook: ''
twitter: ''
linkedin: ''
instagram: ''
flickr: ''
github: ''
#codepen: ''
#telegram: ''
#keybase: ''
#steam: ''
#soundcloud: ''
#stack-overflow: ''
#reddit: ''
#medium:  ''
#tumblr: ''
weibo: ''
vk: ''
#lastfm: ''
blog_url: ''
email: ''

# Advanced settings
plugins:
  - jekyll-remote-theme
