# Theme
remote_theme: 'vivekkrish/cover-card'

# Title and tag line
title: 'My name'
description: 'I am amazing.'

# Images
avatar: 'avatar.jpg'
background: 'background.jpg'
favicon: 'favicon.ico'

# Online profiles
dribbble: 'mydribbble'
facebook: 'myfacebook'
twitter: 'mytwitter'
linkedin: 'mylinkedin'
instagram: 'myinsta'
pinterest: 'mypinterest'
youtube: 'myyoutube'
github: 'mygithub'
#gitlab-user: ''
#codepen: ''
#steam: ''
#soundcloud: ''
#lastfm: ''
#stack-overflow: ''
#reddit: ''
#medium:  ''
#tumblr: ''
weibo: 'myweibo'
vk: 'myvk'
blog_url: 'myblog.blog.com'
email: 'hello@example.com'
messenger: 'myfbchat'

social-order: [github, facebook, twitter, instagram, pinterest, linkedin, youtube, github, vk, weibo, dribbble, messenger, blog_url, email]

# Advanced settings
plugins:
  - jekyll-remote-theme
